display_name: ModMopet

icon: assets/images/flutter_logo.png

summary: A really cool application
group: Application/Emulator
vendor: Kingkor Roy Tirtho
packager: Kingkor Roy Tirtho
packagerEmail: krtirtho@gmail.com
license: GPLv3
url: https://github.com/ModMopet/ModMopet
keywords:
  - games
  - emulation
  - mods
  - switch

generic_name: ModMopet

categories:
  - Games

startup_notify: true
