display_name: ModMopet

icon: assets/images/flutter_logo.png

keywords:
  - emulation
  - mods
  - game
  - switch

generic_name: ModMopet


categories:
  - Games

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
